module.exports = {
	ru: {
		title: 'Пайфу',
		link: 'Прямая ссылка на пайфу',
		player_info: 'Информация об игроках',
		name: 'Имя',
		sex: 'Пол',
		rate: 'Рейтинг',
		dan: 'Дан',
		sexF: 'жен.',
		sexM: 'муж.',
		sexC: 'комп',
		sex_: 'неизв.',
		log: 'Лог',
		dans: ['10 кю', '9 кю', '8 кю', '7 кю', '6 кю', '5 кю', '4 кю', '3 кю', '2 кю', '1 кю',
			'1 дан', '2 дан', '3 дан', '4 дан', '5 дан', '6 дан', '7 дан', '8 дан', '9 дан', '10 дан'
		],
		rounds: ['東1', '東2', '東3', '東4', '南1', '南2', '南3', '南4',
			'西1', '西2', '西3', '西4', '北1', '北2', '北3', '北4'
		],
		seat: ['東', '南', '西', '北'],
		round: 'Раунд',
		honba: 'Хонба',
		reach: 'Риичи',
		dora: 'Дора',
		urador: 'Урадора',
		start: 'Старт',
		draw: 'Взято',
		discard: 'Сброс',
		final: 'Финал',
		pon: 'Пон',
		chi: 'Чи',
		kan: 'Кан',
		chakan: 'Кан',
		nuki: 'Наки',
		ron: 'Рон',
		furikomi: 'Оплата',
		tsumo: 'Цумо',
		from: {
			M: 'выиграл с',
			F: 'выиграла с',
			C: 'выиграл с'
		},
		han: 'хан',
		fu: 'фу',
		score: 'Очков',
		yakulist: 'Список яку',
		ryuukyoku: {
			title: "Ничья",
			tenpai: "Темпай",
			noten: "Нотен",
			yao9: "9 терминалов и благородных",
			reach4: "Четыре риичи",
			ron3: "Тройной рон",
			kan4: "Четыре кана",
			kaze4: "Четыре ветра в сносе",
			nm: "Нагаши манган"
		},
		limits: ['', 'Манган', 'Ханеман', 'Байман', 'Санбайман', 'Якуман'],
		yaku: ['Мензенцумо',
			'Риичи',
			'Иппацу',
			'Чанкан',
			'Риншан кайхо',
			'Хайтей',
			'Хотей',
			'Пинфу',
			'Тан-яо',
			'Иипейко',
			'Свой восток',
			'Свой юг',
			'Свой запад',
			'Свой север',
			'Восток раунда',
			'Юг раунда',
			'Запад раунда',
			'Север раунда',
			'Белый дракон',
			'Зеленый дракон',
			'Красный дракон',
			'Дабл-риичи',
			'Чиитойцу',
			'Чанта',
			'Иццу',
			'Саншоку',
			'Саншоку доко',
			'Сууканцу',
			'Тойтой',
			'Сананко',
			'Шосанген',
			'Хонрото',
			'Рянпейко',
			'Джунчан',
			'Хоницу',
			'Чиницу',
			'Ренхо',
			'Тенхо',
			'Чихо',
			'Дайсанген',
			'Сууанко',
			'Сууанко танки',
			'Цууисо',
			'Рюисо',
			'Чинрото',
			'Чууренпото',
			'Чууренпото 9-стор',
			'Кокушимусо',
			'Кокушимусо 13-стор',
			'Дайсууши',
			'Шосууши',
			'Санканцу',
			'Дора',
			'Урадора',
			'Акадора'
		]
	},
	en: {
		title: 'Paifu',
		link: 'Direct paifu link',
		player_info: 'Player information',
		name: 'Name',
		sex: 'Sex',
		rate: 'Rating',
		dan: 'Dan',
		sexF: 'female',
		sexM: 'male',
		sexC: 'comp',
		sex_: 'NA',
		log: 'Log',
		dans: ['10 kyuu', '9 kyuu', '8 kyuu', '7 kyuu', '6 kyuu', '5 kyuu', '4 kyuu', '3 kyuu', '2 kyuu', '1 kyuu',
			'1 dan', '2 dan', '3 dan', '4 dan', '5 dan', '6 dan', '7 dan', '8 dan', '9 dan', '10 dan'
		],
		rounds: ['東1', '東2', '東3', '東4', '南1', '南2', '南3', '南4',
			'西1', '西2', '西3', '西4', '北1', '北2', '北3', '北4'
		],
		seat: ['東', '南', '西', '北'],
		round: 'Round',
		honba: 'Combo',
		reach: 'Reach',
		dora: 'Dora',
		urador: 'Uradora',
		start: 'Start',
		draw: 'Draw',
		discard: 'Drop',
		final: 'Final',
		pon: 'Pon',
		chi: 'Chii',
		kan: 'Kan',
		chakan: 'Kan',
		nuki: 'Nuki',
		ron: 'Ron',
		furikomi: 'Furikomi',
		tsumo: 'Tsumo',
		from: {
			M: 'win from',
			F: 'win from',
			C: 'win from'
		},
		han: 'han',
		fu: 'fu',
		score: 'Score',
		yakulist: 'Yaku list',
		ryuukyoku: {
			yao9: "9 ends",
			reach4: "Four riichi",
			ron3: "Triple ron",
			kan4: "Four kans",
			kaze4: "Wind discard",
			nm: "Nagashi mangan"
		},
		limits: ['', 'Mangan', 'haneman', 'baiman', 'sanbaiman', 'yakuman'],
		yaku: ['Mentsumo',
			'Riichi',
			'Ippatsu',
			'Chankan',
			'Rinshan kaihou',
			'Haitei raoyue',
			'Houtei raoyui',
			'Pinfu',
			'Tanyao',
			'Iipeiko',
			'Own east',
			'Own south',
			'Own west',
			'Own north',
			'Round east',
			'Round south',
			'Round west',
			'Round north',
			'White dragon',
			'Green dragon',
			'Red dragon',
			'Daburu riichi',
			'Chiitoitsu',
			'Chanta',
			'Ittsu',
			'Sanshoku doujun',
			'Sanshoku doukou',
			'Sankantsu',
			'Toitoi',
			'Sanankou',
			'Shousangen',
			'Honroutou',
			'Ryanpeikou',
			'Junchan',
			'Honitsu',
			'Chinitsu',
			'Renhou',
			'Tenhou',
			'Chihou',
			'Daisangen',
			'Suuankou',
			'Suuankou tanki',
			'Tsuuiisou',
			'Ryuuiisou',
			'Chinroutou',
			'Chuuren pouto',
			'Chuuren pouto 9-wait',
			'Kokushi musou',
			'Kokushi musou 13-wait',
			'Daisuushi',
			'Shousuushi',
			'Suukantsu',
			'Dora',
			'Uradora',
			'Akadora'
		]
	},
	jp: {
		title: 'Paifu',
		link: 'Direct paifu link',
		player_info: 'Player information',
		name: 'Name',
		sex: 'Sex',
		rate: 'Rating',
		dan: 'Dan',
		sexF: 'famale',
		sexM: 'male',
		sexC: 'comp',
		sex_: 'NA',
		log: 'Log',
		dans: ['新人', '9級', '8級', '7級', '6級', '5級', '4級', '3級', '2級', '1級',
			'初段', '二段', '三段', '四段', '五段', '六段', '七段', '八段', '九段', '十段', '天鳳位'
		],
		rounds: ['東1', '東2', '東3', '東4', '南1', '南2', '南3', '南4',
			'西1', '西2', '西3', '西4', '北1', '北2', '北3', '北4'
		],
		seat: ['東', '南', '西', '北'],
		round: 'Round',
		honba: 'Combo',
		reach: 'Reach',
		dora: 'Dora',
		urador: 'Uradora',
		start: 'Start',
		draw: 'Draw',
		discard: 'Drop',
		final: 'Final',
		pon: 'Pon',
		chi: 'Chii',
		kan: 'Kan',
		chakan: 'Kan',
		nuki: 'Nuki',
		ron: 'Ron',
		furikomi: 'フリコミ',
		tsumo: 'ツモ',
		from: {
			M: 'win from',
			F: 'win from',
			C: 'win from'
		},
		han: 'han',
		fu: 'fu',
		score: 'Score',
		yakulist: 'Yaku list',
		ryuukyoku: {
			yao9: "9 ends",
			reach4: "Four riichi",
			ron3: "Triple ron",
			kan4: "Four kans",
			kaze4: "Wind discard",
			nm: "Nagashi mangan"
		},
		limits: ['', 'Mangan', 'haneman', 'baiman', 'sanbaiman', 'yakuman'],
		yaku: ['門前清自摸和',
			'立直',
			'一発',
			'槍槓',
			'嶺上開花',
			'海底摸月',
			'河底撈魚',
			'平和',
			'断幺九',
			'一盃口',
			'自風 東',
			'自風 南',
			'自風 西',
			'自風 北',
			'場風 東',
			'場風 南',
			'場風 西',
			'場風 北',
			'役牌 白',
			'役牌 發',
			'役牌 中',
			'両立直',
			'七対子',
			'混全帯幺九',
			'一気通貫',
			'三色同順',
			'三色同刻',
			'三槓子',
			'対々和',
			'三暗刻',
			'小三元',
			'混老頭',
			'二盃口',
			'純全帯幺九',
			'混一色',
			'清一色',
			'人和',
			'天和',
			'地和',
			'大三元',
			'四暗刻',
			'四暗刻単騎',
			'字一色',
			'緑一色',
			'清老頭',
			'九蓮宝燈',
			'純正九蓮宝燈',
			'国士無双',
			'国士無双１３面',
			'大四喜',
			'小四喜',
			'四槓子',
			'ドラ',
			'裏ドラ',
			'赤ドラ]'
		]
	}
};